# Generated by Django 5.1.4 on 2025-01-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(choices=[('HR', 'HR'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
