# Generated by Django 5.1.4 on 2025-01-13 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_staff',
        ),
    ]
